### ISSUE TITLE
Does not compile with latest bgfx

### ISSUE THREAD

**Issue by pixelpicosean** [floooh/fips-bgfx#13]
I've been trying to make it work with latest bgfx but without any fortune. I've fixed the compiling of `texturec` by adding a new `iqa` lib, but have no idea how to solve the compiling of `shaderc`, which has a new `glslang` dependency.

**Comment by floooh** [comment]
I haven't looked into this for quite a long time. Is this urgent for you?

**Comment by pixelpicosean** [comment]
Not urgent at all, just trying. 

BGFX still feels inconvenient comparing to Oryol. But the mesh vertex updating limitation(once per frame) is another headache. Cannot make a memory friendly sprite-batch implementation the old way. Which graphic backend has this limitation? Is keeping drawing commands the only way to do that now? I am considering using index buffer like what you did with the IMGUI wrapper, without an index buffer I need tons of memory to store vertices of curve shapes.

**Comment by fungos** [comment]
I may try to get it building with latest if needed, just need find some free time next week probably. It shouldn't be too hard to get this new dependency fipsified, it seems it is already a CMake project anyway.

**Comment by pixelpicosean** [comment]
@fungos I'd be very appreciate if you can get it work. BTW is it easy to fipsify a project if it provides CMake file? If it's not that hard I'll give it a try myself.

**Comment by fungos** [comment]
Yes, it is a manual process, but at least most of the hints are already in the CMakeLists.txt of the project. It is easier to translate than other build scripts in general.

**Comment by fungos** [comment]
@pixelpicosean I've fixed bgfx here: https://github.com/fungos/fips-bgfx
Can you test for me?
It requires CMake 2.8.11 or ~~~older~~~ newer to solve a include conflict.
The PR is here: https://github.com/floooh/fips-bgfx/pull/14 failing on travis due the older cmake version.

**Comment by pixelpicosean** [comment]
@fungos I need an older cmake to be able to compile it? I only have v3.7.1 installed for now, with which I've successfully build most targets except the `bgfx-etc2` and `texturec`.

Here's the error message it logs:

```
3rdparty/etc2/ProcessRGB.cpp:208:53: 
error: member reference base type 'v4i' (aka 'uint16 [4]') is not a structure or union
        __m128i d = _mm_loadu_si128((__m128i*)a[i*2].data());
                                              ~~~~~~^~~~~
```

My system: `macOS 10.12.2`

**Comment by fungos** [comment]
Sorry, I meant newer. You should be alright with that version.
What is your compiler? Can you put your output of fips diag in a gist? 
I don't have a mac to test this, so I'm in the dark here, but I may try to help you solve this issue.

This error seems to be broken code over bgfx code base when using sse4. Maybe @bkaradzic can help?

**Comment by pixelpicosean** [comment]
@fungos I've uploaded the log here [fips-bgfx-cli.log](https://gist.github.com/pixelpicosean/e9214988b52e0d077c9a9b40abd5d417)

Have not seen any information about the sse4 though.

**Comment by bkaradzic** [comment]
@fungos Grab latest and try again, it should be fixed.

**Comment by fungos** [comment]
Thanks @bkaradzic!
@pixelpicosean I've updated my fork. As I'm not on my pc I have only windows to test and travis-ci is failing linking over with gcc on ubuntu. But I think this will not be an issue to you.

**Comment by pixelpicosean** [comment]
Thank you people for help. Everything is ok now.
